@url = http://localhost:4004

###
GET {{url}}/learner/Courses
Authorization: Basic alice:alice
###
GET {{url}}/service/risk/Mitigations
Authorization: Basic risk.manager@tester.sap.com:initial
//Authorization: Basic alice:alice

###
//create customer
POST {{url}}/customers/Customers
Content-Type: application/json

{
    "name": "LI",
    "industry": "Bai",
    "country": "CH"
}

